Add async Select and Consume
zbra-dev/maybe pull request #39
Opened 2023-02-03 19:36 UTC by d-nery

This PR also moves Consume from the class to the Extensions and all respective tests from MaybeTests to MaybeExtensionsTests

Solves #12

2023-02-06 23:14 UTC, alercunha requested changes
Consider including more async methods: Or, OrMaybe

2023-02-07 02:20 UTC, alercunha approved these changes

2023-02-07 13:36 UTC, erickotsuka commented
We should have tests for `OrAsync` and `OrMaybeAsync` with a null argument, ensuring it throws the expected exception, like we have for `Or` and `OrMaybe`.

2023-02-07 13:38 UTC, erickotsuka requested changes
We should have tests for `OrAsync` and `OrMaybeAsync` with a null argument, ensuring it throws the expected exception, like we have for `Or` and `OrMaybe`.

2023-02-22 16:32 UTC, erickotsuka approved these changes

2023-02-23 16:13 UTC, merged